### ISSUE TITLE
Broken Shortcuts in Sublime Text 3

### ISSUE THREAD

**Issue by s8m2s** [SublimeText/ElasticTabstops#5]
Seems to be breaking **command + z** (undo), and **command + shift + z** (redo) in Sublime Text 3 Beta Build 3021

**Comment by adzenith** [comment]
Yeah, ST3 changed the way that editing works, so this plugin doesn't work there yet. It's gonna be a bunch of work to change, unfortunately.

**Comment by adzenith** [comment]
Working.
