### ISSUE TITLE
ElasticTabstops  does not work when file is open with multiple views

### ISSUE THREAD

**Issue by pharmafirma** [SublimeText/ElasticTabstops#7]
Hello everyone

The plugin does not always work if the file is open in multiple views. 
How to reproduce:
1. open sublime text 2 (with your plugin installed of course :))
2. open a file which makes use of the elastic tabstop feature (or, create a new file and write at least 2 blocks of text which each contain elastic tabstops).
3. Switch to 2-column: "View" -> "Layout" -> "Columns: 2".
4. Open a second instance of the file: "File" -> "new View into File"
5. Drag one view of the file to the left column and the other to the right, s.t. you see both instances of the file at the same time.
6. The plugin only works in one of both open files (needs some switching around in both views and different text blocks, the bug seems not to happen every time you type).

If you need more information or cannot reproduce it for some other reason, please just reply to this issue and let me know what more information you need...

OS: Debian GNU/Linux 6.0.7
Sublime Text Version: 2.0.1 (build 2217)
Plugin version: The most recent one (just cloned it from Github).

**Comment by adzenith** [comment]
How interesting... easy to repro. I think there's a problem with the way I'm using view.id() to look up selections. I'll get right on it.

**Comment by adzenith** [comment]
It looks like on_modified gets passed the wrong view—it's always passed the original, even if you're modifying the clone.

That's annoying.

I guess instead of just using self.view, I'll have to manually ask the window which view is active. Hrm.

**Comment by adzenith** [comment]
Posted a bug report on the forum.
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=12809&p=50054

**Comment by adzenith** [comment]
Should be fixed—I now check the view ID, and the buffer ID, and which view is the active view. Annoying workaround, but seems to work fine.
